### ISSUE TITLE
Zeiss Scale picometer

### ISSUE THREAD

**Issue by Deadmansshoe** [IMBalENce/EM-tool#1]
Hi,

I am currently using your tools for the images I make at the Zeiss SEM in our university. So far it works great, but I have found a little bug. If the scale is below the nm regime, our microscope (I am not shure if this is the case for every Zeiss microscope) sets the scale in values of pm instead of nm or µm. Therefore, the plugin does not determine the scale of the image all together.
As I looked through the code, I found that the scale is determine to be either ending in nm or um and therefore it does not set the scale, if it is in the um range. This could simply be fixed by adding a check for pm. 

I did fix the error my self, however I am not sure how to properly contribute it to your repository. Could you fix this your self or shell I give it a try?

Additionally, we have a second Zeiss SEM, which stores the scale value not as "Image Pixel Size" instead it uses just "Pixel Size". At the moment, I wrote an additional script, where I replaced the metadata name. However, I am not completely sure how to check it either value exists and to use that one.

Thank you very much for your work on the plugin!

Best
Robin

**Comment by IMBalENce** [comment]
After a bit search and ask, it seems like Zeiss SEMs save the true "pixel size" in two different ways
"Image Pixel Size" represents the true pixel size in the current resolution.
"Pixel Size" is the equivalent pixel size assuming the image is in 1k resolution (1024x???)

Therefore, "Pixel Size" of a 4k image should be 4 times of the "Image Pixel Size" value. Not sure if both are saved in the same image in the latest system (there could be some software updates that changed this). It would be great if you could confirm this on your system.

**Comment by Deadmansshoe** [comment]
Hi Zhou,

sorry that it took quite a while to get back to the issue...

So for me, it really seems like it is really the case, that the "Pixel Size" is for a 1k Image. At least I did give it a try and the same structure in a 3kx2k Image as a width of approximately 3x the width from a 1k image. 

I will add some images from two different microscopes, so you can have a look how the metadata are stored for at least our Zeiss microscope (both are more than 5 years old at least...). Interestingly, sem1 stores the pixel size in the "image pixel size" and the "pixel size" metadata, whereas sem2 seems to only use the "pixel size". I will take a look, if this can be change within the software of the sem. 

[em-tool-zeis-images.zip](https://github.com/IMBalENce/EM-tool/files/9149813/em-tool-zeis-images.zip)

If you need more images or something like that, please let me know.

Kind regards,
Robin

**Comment by IMBalENce** [comment]
Hi Robin,

Sorry for taking so long. Thank you for sending those images. They are very helpful. I have uploaded the new script to both imageJ update site and github. So the two issues you have raised should have been fixed in the new script.
1. Incorrect pixel size unit "pm" was not recognized in the old script.
2. Some Zeiss images does not have "Image Pixel Size" field in metadata. "Pixel Size" value stand for the equivalent pixel size of an 1k image.

Would you like to update the plugin and check if it is working ok? Thank you.

**Comment by IMBalENce** [comment]
This issue should have been fixed now.
